### ISSUE TITLE
Notion link is broken

### ISSUE THREAD

**Issue by lodenrogue** [krlmrr/OpenFantasyRacing#57]
### What happened?

Notion link on readme is broken: https://lydian-emmental-e07.notion.site/F1-Fantasy-League-003e34c960324cd5bd7eee69d59e9130

### URL where issue exists

https://lydian-emmental-e07.notion.site/F1-Fantasy-League-003e34c960324cd5bd7eee69d59e9130

### What browsers are you seeing the problem on?

Brave

**Comment by krlmrr** [comment]
I apologize, I moved away from Notion and forgot to remove the link for the read me.
